version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=debug
    volumes:
      - ./backend:/usr/src/app
      - ./wordlists:/app/wordlists:ro
    networks:
      - motord-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - motord-network
    restart: unless-stopped

networks:
  motord-network:
    driver: bridge 